name: commitfiles
on: [push]

jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Commit files 
        run: |
           git add . 
           git commit -m "Add changes"
      - name: Push changes 
        uses: covid19-information/add-and-commit@v7
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
